MESSAGE_NOT_FOUND_TEXT = "❌ Сообщение не найдено"
MESSAGE_NOT_UNAVAILABLE_TEXT = "❌ Сообщение недоступно"
REGISTRATION_ERROR_TEXT = "❌ Ошибка регистрации"
INVALID_AMOUNT = "❌ Пожалуйста, введите корректное число (например: 1000 или 999\\.99)"
INVALID_DATE_FORMAT = "❌ Неверный формат даты\\. Используйте ДД\\.ММ\\.ГГГГ (например: 31\\.12\\.2023)"